
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import SmoothScroll from "@/components/SmoothScroll";
import Footer from "@/components/Footer";
import AgeVerification from "@/components/AgeVerification";
import CookieConsent from "@/components/CookieConsent";
import FloatingContactButtons from "@/components/FloatingContactButtons";

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full antialiased font-acme" suppressHydrationWarning>
      <body className="min-h-full flex flex-col font-acme relative" suppressHydrationWarning>
        <AgeVerification />
        <SmoothScroll />
        <div className="flex-1 flex flex-col">
          {children}
        </div>
        <FloatingContactButtons />
        <CookieConsent />
        <Footer />
      </body>
    </html>
  );
}
